services:
  db:
    image: postgres:16-alpine
    container_name: waypoint_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=waypoint
      - POSTGRES_PASSWORD=waypoint
      - POSTGRES_DB=waypoint
    volumes:
      - waypoint-db:/var/lib/postgresql/data
    healthcheck:
        # The actual command Docker executes INSIDE the container
        test: ["CMD-SHELL", "pg_isready -U waypoint -d waypoint"]
        interval: 10s   # Run the test every 10 seconds
        timeout: 5s     # Fail if the command takes longer than 5 seconds
        retries: 5      # Mark 'unhealthy' after 5 consecutive failures
        start_period: 10s # Grace period for the DB to boot up initially

volumes:
  waypoint-db:
    driver: local
